#!/usr/bin/env python3
"""Generate codec test vectors using the *real* open3e implementation.

The C codec port in main/o3e_codec.c must agree with open3e byte for byte.
Rather than eyeballing the port, we feed payloads through open3e's own Python
codecs and record the results; test/test_codec.c replays them against C.

Payloads are generated by walking the codec tree, so every leaf gets bytes that
are *valid* for its type.  Uniformly random bytes would instead make roughly 7%
of vectors carry an embedded Python traceback string (invalid UTF-8, month 173,
...), which tests nothing except whether C can reproduce CPython error messages.
Real E3 devices do not send those.

Output: JSON array of {did, name, codec, payload (hex), expected (json)}.
"""
import argparse
import json
import os
import random
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import db_overrides  # noqa: E402

# open3e's O3EUtc/O3EDateTime call datetime.fromtimestamp(), which is local
# time.  Pin the zone so fixtures are reproducible; open3e's own test suite
# does the same (tests/integration/conftest.py).
TZ = "Europe/Berlin"


def load_open3e(src: Path):
    sys.path.insert(0, str(src.parent))
    import open3e.Open3Ecodecs as codecs  # noqa: E402
    import open3e.Open3Edatapoints as datapoints  # noqa: E402
    import open3e.Open3Eenums as enums  # noqa: E402
    return codecs, datapoints, enums


def make_payload(rng: random.Random, codec, C, E) -> bytes:
    """Build a payload that is valid for `codec`, recursing into sub-types."""
    kind = type(codec).__name__
    n = codec.string_len

    if kind == "O3EComplexType":
        return b"".join(make_payload(rng, s, C, E) for s in codec.subTypes)

    if kind == "O3EArray":
        out = b""
        for sub in codec.subTypes:
            for _ in range(codec.len):
                out += make_payload(rng, sub, C, E)
        return out.ljust(n, b"\0")[:n]

    if kind == "O3EList":
        # Mirror the decoder's own walk: a field literally named "Count" gives
        # the repeat count, any O3EComplexType field is the repeated element,
        # and anything else (e.g. "GrandTotal" on DIDs 264/266) is a plain
        # scalar that still occupies its bytes.
        elem = next((s for s in codec.subTypes if type(s).__name__ == "O3EComplexType"), None)
        fixed = sum(s.string_len for s in codec.subTypes if s is not elem)
        capacity = (n - fixed) // elem.string_len if elem else 0
        count = rng.randrange(0, min(3, capacity) + 1) if capacity > 0 else 0

        out = b""
        for sub in codec.subTypes:
            if sub.id.lower() == "count":
                out += count.to_bytes(sub.string_len, "little")
            elif sub is elem:
                for _ in range(count):
                    out += make_payload(rng, sub, C, E)
            else:
                out += make_payload(rng, sub, C, E)
        return out.ljust(n, b"\0")[:n]

    if kind == "O3ESwitch":
        keys = list(codec.cases.keys())
        if keys and rng.random() < 0.85:
            val = rng.choice(keys)
            branch = codec.cases[val]
        else:
            val = rng.randrange(200, 256)  # exercise the default / no-match path
            branch = codec.default
        body = make_payload(rng, branch, C, E) if branch is not None else b""
        return (bytes([val]) + body).ljust(n, b"\0")[:n]

    if kind == "O3EEnum":
        table = E.E3Enums.get(codec.listStr, {})
        # mostly hit a mapped value, sometimes miss on purpose
        if table and rng.random() < 0.8:
            val = rng.choice(list(table.keys()))
        else:
            val = rng.randrange(0, 256 ** n)
        return int(val).to_bytes(n, "little", signed=False)

    if kind == "O3EUtf8":
        text = "".join(rng.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_ ") for _ in range(n))
        return text.encode("ascii")[:n]

    if kind == "O3EBool":
        return bytes([rng.randrange(0, 2)])

    if kind == "O3ESdate":
        return bytes([rng.randrange(1, 29), rng.randrange(1, 13), rng.randrange(0, 100)])

    if kind == "O3EDateTime":
        if codec.timeformat == "VM":
            b = bytearray(n)
            b[0] = 20
            b[1] = rng.randrange(0, 100)          # year = b0*100 + b1
            b[2] = rng.randrange(1, 13)           # month
            b[3] = rng.randrange(1, 29)           # day
            b[4] = rng.randrange(1, 8)            # weekday, unused by open3e
            b[5] = rng.randrange(0, 24)           # hour
            b[6] = rng.randrange(0, 60)           # minute
            b[7] = rng.randrange(0, 60)           # second
            return bytes(b)
        # 'ts': 6-byte little-endian unix timestamp
        ts = rng.randrange(0, 2_000_000_000)
        return ts.to_bytes(6, "little")

    if kind == "O3EUtc":
        # keep inside a range strftime can represent everywhere
        return rng.randrange(0, 2_000_000_000).to_bytes(4, "little")

    if kind == "O3EFloat32":
        import struct
        while True:
            raw = bytes(rng.randrange(256) for _ in range(4))
            val = struct.unpack("<f", raw)[0]
            if val == val and abs(val) != float("inf"):  # reject NaN/Inf
                return raw

    # RawCodec, O3EInt*, O3EByteVal, O3ESoftVers, O3EMacAddr, O3EIp4Addr,
    # O3EStime: every byte pattern is valid.
    return bytes(rng.randrange(256) for _ in range(n))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--open3e", type=Path,
                    default=Path(__file__).resolve().parent.parent / ".cache" / "open3e")
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("-n", "--per-did", type=int, default=3)
    ap.add_argument("--seed", type=int, default=20260705)
    args = ap.parse_args()

    os.environ["TZ"] = TZ
    time.tzset()

    C, D, E = load_open3e(args.open3e / "src" / "open3e")
    C.flag_rawmode = False
    C.flag_binary = False

    rng = random.Random(args.seed)
    dids = D.dataIdentifiers["dids"]

    # Same corrections the firmware's database carries, so the C port and
    # open3e are compared on identical definitions.
    n = db_overrides.apply_to_codecs(dids, C)
    print(f"applied {n} sensor error enums", file=sys.stderr)
    vectors, failed = [], {}
    for did in sorted(dids):
        codec = dids[did]
        for _ in range(args.per_did):
            payload = make_payload(rng, codec, C, E)
            if len(payload) != codec.string_len:
                payload = payload.ljust(codec.string_len, b"\0")[:codec.string_len]
            try:
                expected = json.dumps(codec.decode(payload), ensure_ascii=False)
            except Exception as exc:  # noqa: BLE001
                failed.setdefault(type(codec).__name__, []).append(f"did {did}: {exc}")
                continue
            vectors.append({
                "did": did,
                "name": codec.id,
                "codec": type(codec).__name__,
                "payload": payload.hex(),
                "expected": expected,
            })

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(vectors, indent=1, ensure_ascii=False), encoding="utf-8")

    print(f"{len(vectors)} vectors -> {args.output}  (TZ={TZ})")
    if failed:
        print("open3e refused to decode these (excluded):", file=sys.stderr)
        for kind, msgs in sorted(failed.items()):
            print(f"  {kind}: {len(msgs)}  e.g. {msgs[0]}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
